spring.application.name=api-gateway
server.port=8080

# Logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=http://localhost:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=http://localhost:8085
spring.cloud.gateway.routes[1].predicates[0]=Path=/payments/**
